name: Daily Weather Alert

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 8:00 AM UTC daily
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  check-weather:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run weather check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        EXTERNAL_APPLICATION_KEY: ${{ secrets.EXTERNAL_APPLICATION_KEY }}
        EXTERNAL_API_KEY: ${{ secrets.EXTERNAL_API_KEY }}
        MAC_ADDRESS: ${{ secrets.MAC_ADDRESS }}
        BASE_URL: ${{ secrets.BASE_URL }}
        WHATSAPP_API_URL: ${{ secrets.WHATSAPP_API_URL }}
        WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
        WHATSAPP_API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
      run: python src/alert.py

